# create as many configuration files as you want

client:
  pid: 0
  server_host: "192.168.0.40"
  log_file_postfix: "UNFILTERED"                     # a string to append to the CSV file names
  server_udp_port: 9000
  server_ping_port: 9001
  server_udp_dns_port: 53
  server_tcp_http_port: 80
  server_tcp_dns_port: 53
  tests:
    idle_state_of_device: 
      enable: true
    idle_state_of_process:
      enable: true
    http_throughput:
      enable: true
    ping:
      enable: true
      countSamples: 100
    jitter:
      enable: true
      countDifferences: 100
    http_burst:
      enable: true
    http_rate:
      enable: true
      duration: 10
